/* This file is generated by scripts automatively.
 * do not change it by hand.
 */

#include "../../include/GNeuron.h"
#include "../../include/GSynapse.h"
#include "../utils/TypeFunc.h"

void* (*createType[])() = { createConstant, createPoisson, createLIF, createExp};

size_t (*getTypeSize[])() = { getConstantSize, getPoissonSize, getLIFSize, getExpSize};

int (*allocType[])(void *, int) = { allocConstant, allocPoisson, allocLIF, allocExp};

int (*addTypeConnection[])(void *, int *) = { NULL, NULL, NULL, addExpConnection};

void (*mpiSendType[])(void *data, int rank, int offset, int size) = { mpiSendConstant, mpiSendPoisson, mpiSendLIF, mpiSendExp};

void (*mpiRecvType[])(void **data, int rank, int size) = { mpiRecvConstant, mpiRecvPoisson, mpiRecvLIF, mpiRecvExp};

