/* This file is generated by scripts automatively.
 * do not change it by hand.
 */

#include "../gpu_utils/gpu_func.h"

#include "../../include/GNeuron.h"
#include "../../include/GSynapse.h"
#include "../utils/TypeFunc.h"

int (*cudaAllocType[])(void *, void *, int) = { cudaAllocConstant, cudaAllocPoisson, cudaAllocArray, cudaAllocLIF, cudaAllocExp};

int (*cudaFreeType[])(void *) = { cudaFreeConstant, cudaFreePoisson, cudaFreeArray, cudaFreeLIF, cudaFreeExp};

int (*cudaUpdateType[])(void *, int, int, BlockSize*) = { cudaUpdateConstant, cudaUpdatePoisson, cudaUpdateArray, cudaUpdateLIF, cudaUpdateExp};

int (*cudaUpdateAllType[])(void *, int, int, BlockSize*) = { cudaUpdateConstant, cudaUpdatePoisson, cudaUpdateArray, cudaUpdateAllLIF, cudaUpdateAllExp};

